### PR TITLE
Refactor pmpm to claims based on internal tuva data

### PR DESCRIPTION
**Pull request by bentuvan**

### CODE REVIEW

**Review by aneiderhiser — CHANGES_REQUESTED** [review]
A couple comments:
- I pulled this branch and was able to run this fine locally (yay!)
- Rename the pmpm_and_utilization_builder table to pmpm_builder
- Add isnull() or coalesce() to the spend columns in pmpm_builder table to make the nulls zeros
- sum(medical_spend) does not add up to sum(paid_amount) from the base table.  I assume this is because some patients have claims that they don't have eligibility spans for but I didn't look into this

**Comment by aneiderhiser** [comment]
@thutuva - I assume you'll want to be a reviewer on every PR for the foreseeable future, but may not be necessary on this one.  I think we just merge this after Ben makes the changes above.  When we're ready to actually release it as a package we'll need to do another PR and you can review that.

**Comment by bentuvan** [comment]
The changes requested have been addressed. Yes, the totals don't match up with the underlaying table totals because of eligibility constraints on the pmpm builder table.

**Comment by aneiderhiser** [comment]
@bentuvan i reviewed and tested these changes snowflake - looks great thanks for making them!

**Review by aneiderhiser — APPROVED** [review]

**Pull request merged**
